import { createFileRoute } from "@tanstack/react-router";
import { AppLayout } from "@/components/app-layout";
import { AppTopbar } from "@/components/app-topbar";
import { StatusBadge } from "@/components/status-badge";
import { reports } from "@/lib/mock-data";
import { FileText, FileSpreadsheet, Download, MoreVertical, RotateCw, RefreshCw } from "lucide-react";

export const Route = createFileRoute("/reports")({
  component: ReportsPage,
  head: () => ({ meta: [{ title: "Reports — VendorPulse" }] }),
});

function ReportsPage() {
  const iconFor = (t: string) =>
    t === "xlsx" ? <FileSpreadsheet className="size-5 text-emerald-400" /> : t === "csv" ? <FileSpreadsheet className="size-5 text-blue-400" /> : <FileText className="size-5 text-rose-400" />;

  return (
    <AppLayout>
      <AppTopbar cta="Generate Report" />
      <div className="px-4 lg:px-8 pb-10 space-y-6">
        <div className="pt-6">
          <h1 className="text-3xl font-bold tracking-tight">Report Generation History</h1>
          <p className="text-sm text-muted-foreground mt-1">Audit, export and re-run vendor reports.</p>
        </div>

        <div className="glass-card rounded-2xl p-2">
          <div className="flex items-center justify-between p-3">
            <div className="flex items-center gap-2">
              <select className="h-9 rounded-lg bg-background border border-border px-3 text-xs"><option>All Types</option><option>PDF</option><option>CSV</option><option>XLSX</option></select>
              <select className="h-9 rounded-lg bg-background border border-border px-3 text-xs"><option>All Status</option><option>Ready</option><option>Failed</option></select>
            </div>
            <button className="size-9 grid place-items-center rounded-lg border border-border bg-background hover:bg-accent"><RefreshCw className="size-4" /></button>
          </div>
          <div className="overflow-x-auto scrollbar-thin">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-[11px] uppercase tracking-widest text-muted-foreground border-y border-border bg-muted/30">
                  <th className="text-left py-3 px-4 font-medium">Report Name</th>
                  <th className="text-left py-3 px-4 font-medium">Generated By</th>
                  <th className="text-left py-3 px-4 font-medium">Date</th>
                  <th className="text-left py-3 px-4 font-medium">Status</th>
                  <th className="text-left py-3 px-4 font-medium">Size</th>
                  <th className="text-right py-3 px-4 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r.name} className="border-b border-border/40 hover:bg-accent/30 transition-colors">
                    <td className="py-4 px-4">
                      <div className="flex items-center gap-3">
                        <div className="size-9 rounded-lg bg-muted grid place-items-center">{iconFor(r.type)}</div>
                        <span className="font-medium">{r.name}</span>
                      </div>
                    </td>
                    <td className="py-4 px-4 text-muted-foreground">{r.by}</td>
                    <td className="py-4 px-4 text-muted-foreground">{r.date}</td>
                    <td className="py-4 px-4"><StatusBadge status={r.status} /></td>
                    <td className="py-4 px-4 text-muted-foreground">{r.size}</td>
                    <td className="py-4 px-4">
                      <div className="flex items-center justify-end gap-1">
                        {r.status === "Failed" ? (
                          <button className="size-8 grid place-items-center rounded-lg hover:bg-accent text-primary"><RotateCw className="size-4" /></button>
                        ) : (
                          <button className="size-8 grid place-items-center rounded-lg hover:bg-accent text-primary"><Download className="size-4" /></button>
                        )}
                        <button className="size-8 grid place-items-center rounded-lg hover:bg-accent"><MoreVertical className="size-4" /></button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="flex items-center justify-between p-3 text-xs text-muted-foreground">
            <span>Showing 1–{reports.length} of 42 reports</span>
            <div className="flex gap-1">
              <button className="size-8 grid place-items-center rounded-lg border border-border">‹</button>
              <button className="size-8 grid place-items-center rounded-lg border border-border">›</button>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
